// dot -Tpdf Makefile.dot > Makefile.pdf && open Makefile.pdf
digraph {
    node [colorscheme=set14]
    
    "all" [shape=parallelogram style=solid color=1 penwidth=2]
    "msla" [shape=parallelogram style=solid color=2 penwidth=2]
    "mrvaserver" [shape=rectangle style=solid color=3 penwidth=2]
    "clean" [shape=parallelogram style=solid color=4 penwidth=2]

    "all" -> "msla"
}
